// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: gateway_interceptor.proto

package interceptorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayInterceptor_Describe_FullMethodName                 = "/openshell.gateway_interceptor.v1.GatewayInterceptor/Describe"
	GatewayInterceptor_SnapshotProviderProfiles_FullMethodName = "/openshell.gateway_interceptor.v1.GatewayInterceptor/SnapshotProviderProfiles"
	GatewayInterceptor_Evaluate_FullMethodName                 = "/openshell.gateway_interceptor.v1.GatewayInterceptor/Evaluate"
)

// GatewayInterceptorClient is the client API for GatewayInterceptor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayInterceptor lets an external governance service evaluate gateway
// control-plane operations after OpenShell admission and before or after the
// gateway applies the operation.
type GatewayInterceptorClient interface {
	// Describe returns the interceptor manifest and declared bindings.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*InterceptorManifest, error)
	// SnapshotProviderProfiles returns the interceptor's current provider
	// profile snapshot when the manifest advertises provider_profiles = true.
	SnapshotProviderProfiles(ctx context.Context, in *ProviderProfileSnapshotRequest, opts ...grpc.CallOption) (*ProviderProfileSnapshot, error)
	// Evaluate returns an allow, deny, or mutation decision for one operation
	// phase.
	Evaluate(ctx context.Context, in *InterceptorEvaluation, opts ...grpc.CallOption) (*InterceptorResult, error)
}

type gatewayInterceptorClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayInterceptorClient(cc grpc.ClientConnInterface) GatewayInterceptorClient {
	return &gatewayInterceptorClient{cc}
}

func (c *gatewayInterceptorClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*InterceptorManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterceptorManifest)
	err := c.cc.Invoke(ctx, GatewayInterceptor_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayInterceptorClient) SnapshotProviderProfiles(ctx context.Context, in *ProviderProfileSnapshotRequest, opts ...grpc.CallOption) (*ProviderProfileSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderProfileSnapshot)
	err := c.cc.Invoke(ctx, GatewayInterceptor_SnapshotProviderProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayInterceptorClient) Evaluate(ctx context.Context, in *InterceptorEvaluation, opts ...grpc.CallOption) (*InterceptorResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterceptorResult)
	err := c.cc.Invoke(ctx, GatewayInterceptor_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayInterceptorServer is the server API for GatewayInterceptor service.
// All implementations must embed UnimplementedGatewayInterceptorServer
// for forward compatibility.
//
// GatewayInterceptor lets an external governance service evaluate gateway
// control-plane operations after OpenShell admission and before or after the
// gateway applies the operation.
type GatewayInterceptorServer interface {
	// Describe returns the interceptor manifest and declared bindings.
	Describe(context.Context, *DescribeRequest) (*InterceptorManifest, error)
	// SnapshotProviderProfiles returns the interceptor's current provider
	// profile snapshot when the manifest advertises provider_profiles = true.
	SnapshotProviderProfiles(context.Context, *ProviderProfileSnapshotRequest) (*ProviderProfileSnapshot, error)
	// Evaluate returns an allow, deny, or mutation decision for one operation
	// phase.
	Evaluate(context.Context, *InterceptorEvaluation) (*InterceptorResult, error)
	mustEmbedUnimplementedGatewayInterceptorServer()
}

// UnimplementedGatewayInterceptorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayInterceptorServer struct{}

func (UnimplementedGatewayInterceptorServer) Describe(context.Context, *DescribeRequest) (*InterceptorManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedGatewayInterceptorServer) SnapshotProviderProfiles(context.Context, *ProviderProfileSnapshotRequest) (*ProviderProfileSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotProviderProfiles not implemented")
}
func (UnimplementedGatewayInterceptorServer) Evaluate(context.Context, *InterceptorEvaluation) (*InterceptorResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedGatewayInterceptorServer) mustEmbedUnimplementedGatewayInterceptorServer() {}
func (UnimplementedGatewayInterceptorServer) testEmbeddedByValue()                            {}

// UnsafeGatewayInterceptorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayInterceptorServer will
// result in compilation errors.
type UnsafeGatewayInterceptorServer interface {
	mustEmbedUnimplementedGatewayInterceptorServer()
}

func RegisterGatewayInterceptorServer(s grpc.ServiceRegistrar, srv GatewayInterceptorServer) {
	// If the following call panics, it indicates UnimplementedGatewayInterceptorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayInterceptor_ServiceDesc, srv)
}

func _GatewayInterceptor_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayInterceptorServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayInterceptor_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayInterceptorServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayInterceptor_SnapshotProviderProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderProfileSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayInterceptorServer).SnapshotProviderProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayInterceptor_SnapshotProviderProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayInterceptorServer).SnapshotProviderProfiles(ctx, req.(*ProviderProfileSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayInterceptor_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterceptorEvaluation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayInterceptorServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayInterceptor_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayInterceptorServer).Evaluate(ctx, req.(*InterceptorEvaluation))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayInterceptor_ServiceDesc is the grpc.ServiceDesc for GatewayInterceptor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayInterceptor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openshell.gateway_interceptor.v1.GatewayInterceptor",
	HandlerType: (*GatewayInterceptorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _GatewayInterceptor_Describe_Handler,
		},
		{
			MethodName: "SnapshotProviderProfiles",
			Handler:    _GatewayInterceptor_SnapshotProviderProfiles_Handler,
		},
		{
			MethodName: "Evaluate",
			Handler:    _GatewayInterceptor_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway_interceptor.proto",
}
