// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: gateway_interceptor.proto

package interceptorv1

import (
	openshellv1 "github.com/NVIDIA/OpenShell/sdk/go/proto/openshellv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayInterceptorPhase int32

const (
	GatewayInterceptorPhase_GATEWAY_INTERCEPTOR_PHASE_UNSPECIFIED      GatewayInterceptorPhase = 0
	GatewayInterceptorPhase_GATEWAY_INTERCEPTOR_PHASE_MODIFY_OPERATION GatewayInterceptorPhase = 2
	GatewayInterceptorPhase_GATEWAY_INTERCEPTOR_PHASE_VALIDATE         GatewayInterceptorPhase = 3
	GatewayInterceptorPhase_GATEWAY_INTERCEPTOR_PHASE_POST_COMMIT      GatewayInterceptorPhase = 4
)

// Enum value maps for GatewayInterceptorPhase.
var (
	GatewayInterceptorPhase_name = map[int32]string{
		0: "GATEWAY_INTERCEPTOR_PHASE_UNSPECIFIED",
		2: "GATEWAY_INTERCEPTOR_PHASE_MODIFY_OPERATION",
		3: "GATEWAY_INTERCEPTOR_PHASE_VALIDATE",
		4: "GATEWAY_INTERCEPTOR_PHASE_POST_COMMIT",
	}
	GatewayInterceptorPhase_value = map[string]int32{
		"GATEWAY_INTERCEPTOR_PHASE_UNSPECIFIED":      0,
		"GATEWAY_INTERCEPTOR_PHASE_MODIFY_OPERATION": 2,
		"GATEWAY_INTERCEPTOR_PHASE_VALIDATE":         3,
		"GATEWAY_INTERCEPTOR_PHASE_POST_COMMIT":      4,
	}
)

func (x GatewayInterceptorPhase) Enum() *GatewayInterceptorPhase {
	p := new(GatewayInterceptorPhase)
	*p = x
	return p
}

func (x GatewayInterceptorPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GatewayInterceptorPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_interceptor_proto_enumTypes[0].Descriptor()
}

func (GatewayInterceptorPhase) Type() protoreflect.EnumType {
	return &file_gateway_interceptor_proto_enumTypes[0]
}

func (x GatewayInterceptorPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GatewayInterceptorPhase.Descriptor instead.
func (GatewayInterceptorPhase) EnumDescriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{0}
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_gateway_interceptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{0}
}

type ProviderProfileSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderProfileSnapshotRequest) Reset() {
	*x = ProviderProfileSnapshotRequest{}
	mi := &file_gateway_interceptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderProfileSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderProfileSnapshotRequest) ProtoMessage() {}

func (x *ProviderProfileSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderProfileSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ProviderProfileSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{1}
}

type InterceptorEvaluation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configured interceptor instance name.
	InterceptorName string `protobuf:"bytes,1,opt,name=interceptor_name,json=interceptorName,proto3" json:"interceptor_name,omitempty"`
	// Manifest binding id selected for this evaluation.
	BindingId string `protobuf:"bytes,2,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	// Public gRPC service name, e.g. "openshell.v1.OpenShell".
	Service string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	// Public gRPC method name, e.g. "CreateSandbox".
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	// Caller identity summary. Values are intentionally non-secret.
	Principal map[string]string `protobuf:"bytes,5,rep,name=principal,proto3" json:"principal,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Exactly one phase payload is set for each evaluation.
	//
	// Types that are valid to be assigned to Phase:
	//
	//	*InterceptorEvaluation_ModifyOperation
	//	*InterceptorEvaluation_Validate
	//	*InterceptorEvaluation_PostCommit
	Phase         isInterceptorEvaluation_Phase `protobuf_oneof:"phase"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptorEvaluation) Reset() {
	*x = InterceptorEvaluation{}
	mi := &file_gateway_interceptor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptorEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptorEvaluation) ProtoMessage() {}

func (x *InterceptorEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptorEvaluation.ProtoReflect.Descriptor instead.
func (*InterceptorEvaluation) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{2}
}

func (x *InterceptorEvaluation) GetInterceptorName() string {
	if x != nil {
		return x.InterceptorName
	}
	return ""
}

func (x *InterceptorEvaluation) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *InterceptorEvaluation) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *InterceptorEvaluation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InterceptorEvaluation) GetPrincipal() map[string]string {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *InterceptorEvaluation) GetPhase() isInterceptorEvaluation_Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *InterceptorEvaluation) GetModifyOperation() *ModifyOperationEvaluation {
	if x != nil {
		if x, ok := x.Phase.(*InterceptorEvaluation_ModifyOperation); ok {
			return x.ModifyOperation
		}
	}
	return nil
}

func (x *InterceptorEvaluation) GetValidate() *ValidateEvaluation {
	if x != nil {
		if x, ok := x.Phase.(*InterceptorEvaluation_Validate); ok {
			return x.Validate
		}
	}
	return nil
}

func (x *InterceptorEvaluation) GetPostCommit() *PostCommitEvaluation {
	if x != nil {
		if x, ok := x.Phase.(*InterceptorEvaluation_PostCommit); ok {
			return x.PostCommit
		}
	}
	return nil
}

type isInterceptorEvaluation_Phase interface {
	isInterceptorEvaluation_Phase()
}

type InterceptorEvaluation_ModifyOperation struct {
	// Evaluation that may modify the prepared gateway operation.
	ModifyOperation *ModifyOperationEvaluation `protobuf:"bytes,6,opt,name=modify_operation,json=modifyOperation,proto3,oneof"`
}

type InterceptorEvaluation_Validate struct {
	// Evaluation that may reject, but not mutate, the prepared operation.
	Validate *ValidateEvaluation `protobuf:"bytes,7,opt,name=validate,proto3,oneof"`
}

type InterceptorEvaluation_PostCommit struct {
	// Evaluation after the gateway operation has completed successfully.
	PostCommit *PostCommitEvaluation `protobuf:"bytes,8,opt,name=post_commit,json=postCommit,proto3,oneof"`
}

func (*InterceptorEvaluation_ModifyOperation) isInterceptorEvaluation_Phase() {}

func (*InterceptorEvaluation_Validate) isInterceptorEvaluation_Phase() {}

func (*InterceptorEvaluation_PostCommit) isInterceptorEvaluation_Phase() {}

type ModifyOperationEvaluation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway-prepared operation the gateway proposes to execute.
	ProposedOperation *structpb.Struct `protobuf:"bytes,1,opt,name=proposed_operation,json=proposedOperation,proto3" json:"proposed_operation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModifyOperationEvaluation) Reset() {
	*x = ModifyOperationEvaluation{}
	mi := &file_gateway_interceptor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyOperationEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyOperationEvaluation) ProtoMessage() {}

func (x *ModifyOperationEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyOperationEvaluation.ProtoReflect.Descriptor instead.
func (*ModifyOperationEvaluation) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyOperationEvaluation) GetProposedOperation() *structpb.Struct {
	if x != nil {
		return x.ProposedOperation
	}
	return nil
}

type ValidateEvaluation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway-prepared operation after earlier interceptor modifications.
	ProposedOperation *structpb.Struct `protobuf:"bytes,1,opt,name=proposed_operation,json=proposedOperation,proto3" json:"proposed_operation,omitempty"`
	// Optional read-only gateway state loaded before applying the operation.
	CurrentState  *structpb.Struct `protobuf:"bytes,2,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateEvaluation) Reset() {
	*x = ValidateEvaluation{}
	mi := &file_gateway_interceptor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEvaluation) ProtoMessage() {}

func (x *ValidateEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEvaluation.ProtoReflect.Descriptor instead.
func (*ValidateEvaluation) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateEvaluation) GetProposedOperation() *structpb.Struct {
	if x != nil {
		return x.ProposedOperation
	}
	return nil
}

func (x *ValidateEvaluation) GetCurrentState() *structpb.Struct {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

type PostCommitEvaluation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protobuf JSON-shaped response returned by the committed gateway operation.
	CommittedResponse *structpb.Struct `protobuf:"bytes,1,opt,name=committed_response,json=committedResponse,proto3" json:"committed_response,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PostCommitEvaluation) Reset() {
	*x = PostCommitEvaluation{}
	mi := &file_gateway_interceptor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommitEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommitEvaluation) ProtoMessage() {}

func (x *PostCommitEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommitEvaluation.ProtoReflect.Descriptor instead.
func (*PostCommitEvaluation) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{5}
}

func (x *PostCommitEvaluation) GetCommittedResponse() *structpb.Struct {
	if x != nil {
		return x.CommittedResponse
	}
	return nil
}

type InterceptorResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False denies the operation before side effects for modify_operation and
	// validate. Post-commit denial is invalid.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Human-readable reason for logs and denied gRPC status messages.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional gRPC status code name for denials, e.g. "PERMISSION_DENIED".
	StatusCode string `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// RFC 6902 JSON patches. Only valid during modify_operation.
	Patches []*JsonPatch `protobuf:"bytes,4,rep,name=patches,proto3" json:"patches,omitempty"`
	// Non-secret annotations included in gateway logs.
	LogAnnotations map[string]string `protobuf:"bytes,5,rep,name=log_annotations,json=logAnnotations,proto3" json:"log_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterceptorResult) Reset() {
	*x = InterceptorResult{}
	mi := &file_gateway_interceptor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptorResult) ProtoMessage() {}

func (x *InterceptorResult) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptorResult.ProtoReflect.Descriptor instead.
func (*InterceptorResult) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{6}
}

func (x *InterceptorResult) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *InterceptorResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InterceptorResult) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *InterceptorResult) GetPatches() []*JsonPatch {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *InterceptorResult) GetLogAnnotations() map[string]string {
	if x != nil {
		return x.LogAnnotations
	}
	return nil
}

type InterceptorManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable interceptor name declared by the service.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Bindings declared by the interceptor service.
	Bindings []*InterceptorBinding `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	// Optional default failure policy for bindings without their own policy.
	// Supported values are "fail_closed" and "fail_open".
	FailurePolicy string `protobuf:"bytes,3,opt,name=failure_policy,json=failurePolicy,proto3" json:"failure_policy,omitempty"`
	// True when this interceptor implements SnapshotProviderProfiles.
	ProviderProfiles bool `protobuf:"varint,4,opt,name=provider_profiles,json=providerProfiles,proto3" json:"provider_profiles,omitempty"`
	// Exact JWT audience this service verifies on inbound OpenShell calls.
	// After authenticated Describe succeeds, the gateway refuses to start unless
	// this matches the operator-configured audience. A strict verifier may reject
	// an incorrect audience before returning this manifest. Empty skips this
	// post-authentication consistency check.
	ExpectedAudience string `protobuf:"bytes,5,opt,name=expected_audience,json=expectedAudience,proto3" json:"expected_audience,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InterceptorManifest) Reset() {
	*x = InterceptorManifest{}
	mi := &file_gateway_interceptor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptorManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptorManifest) ProtoMessage() {}

func (x *InterceptorManifest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptorManifest.ProtoReflect.Descriptor instead.
func (*InterceptorManifest) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{7}
}

func (x *InterceptorManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterceptorManifest) GetBindings() []*InterceptorBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *InterceptorManifest) GetFailurePolicy() string {
	if x != nil {
		return x.FailurePolicy
	}
	return ""
}

func (x *InterceptorManifest) GetProviderProfiles() bool {
	if x != nil {
		return x.ProviderProfiles
	}
	return false
}

func (x *InterceptorManifest) GetExpectedAudience() string {
	if x != nil {
		return x.ExpectedAudience
	}
	return ""
}

type ProviderProfileSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque source revision used for cache freshness and sandbox reload checks.
	Revision string `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// Complete profile snapshot vended by this source.
	Profiles      []*openshellv1.ProviderProfile `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderProfileSnapshot) Reset() {
	*x = ProviderProfileSnapshot{}
	mi := &file_gateway_interceptor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderProfileSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderProfileSnapshot) ProtoMessage() {}

func (x *ProviderProfileSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderProfileSnapshot.ProtoReflect.Descriptor instead.
func (*ProviderProfileSnapshot) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderProfileSnapshot) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ProviderProfileSnapshot) GetProfiles() []*openshellv1.ProviderProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type InterceptorBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable binding id used for config overrides and audit logs.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// RPC selector. Selectors are intentionally tied to the public API shape.
	Selector *InterceptorSelector `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	// Phases this binding wants to evaluate.
	Phases []GatewayInterceptorPhase `protobuf:"varint,3,rep,packed,name=phases,proto3,enum=openshell.gateway_interceptor.v1.GatewayInterceptorPhase" json:"phases,omitempty"`
	// Optional binding-specific failure policy.
	// Supported values are "fail_closed" and "fail_open".
	// Bindings that include post_commit must resolve to "fail_open" because the
	// gateway operation has already committed before that phase runs.
	FailurePolicy string `protobuf:"bytes,4,opt,name=failure_policy,json=failurePolicy,proto3" json:"failure_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptorBinding) Reset() {
	*x = InterceptorBinding{}
	mi := &file_gateway_interceptor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptorBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptorBinding) ProtoMessage() {}

func (x *InterceptorBinding) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptorBinding.ProtoReflect.Descriptor instead.
func (*InterceptorBinding) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{9}
}

func (x *InterceptorBinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InterceptorBinding) GetSelector() *InterceptorSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *InterceptorBinding) GetPhases() []GatewayInterceptorPhase {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *InterceptorBinding) GetFailurePolicy() string {
	if x != nil {
		return x.FailurePolicy
	}
	return ""
}

type InterceptorSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full selector form: "openshell.v1.OpenShell/CreateSandbox".
	Rpc string `protobuf:"bytes,1,opt,name=rpc,proto3" json:"rpc,omitempty"`
	// Structured service/method form. If rpc is set, it takes precedence.
	Service       string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method        string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptorSelector) Reset() {
	*x = InterceptorSelector{}
	mi := &file_gateway_interceptor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptorSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptorSelector) ProtoMessage() {}

func (x *InterceptorSelector) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptorSelector.ProtoReflect.Descriptor instead.
func (*InterceptorSelector) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{10}
}

func (x *InterceptorSelector) GetRpc() string {
	if x != nil {
		return x.Rpc
	}
	return ""
}

func (x *InterceptorSelector) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *InterceptorSelector) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type JsonPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonPatch) Reset() {
	*x = JsonPatch{}
	mi := &file_gateway_interceptor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonPatch) ProtoMessage() {}

func (x *JsonPatch) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_interceptor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonPatch.ProtoReflect.Descriptor instead.
func (*JsonPatch) Descriptor() ([]byte, []int) {
	return file_gateway_interceptor_proto_rawDescGZIP(), []int{11}
}

func (x *JsonPatch) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *JsonPatch) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *JsonPatch) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *JsonPatch) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

var File_gateway_interceptor_proto protoreflect.FileDescriptor

const file_gateway_interceptor_proto_rawDesc = "" +
	"\n" +
	"\x19gateway_interceptor.proto\x12 openshell.gateway_interceptor.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0fopenshell.proto\"\x11\n" +
	"\x0fDescribeRequest\" \n" +
	"\x1eProviderProfileSnapshotRequest\"\xd9\x04\n" +
	"\x15InterceptorEvaluation\x12)\n" +
	"\x10interceptor_name\x18\x01 \x01(\tR\x0finterceptorName\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x02 \x01(\tR\tbindingId\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12d\n" +
	"\tprincipal\x18\x05 \x03(\v2F.openshell.gateway_interceptor.v1.InterceptorEvaluation.PrincipalEntryR\tprincipal\x12h\n" +
	"\x10modify_operation\x18\x06 \x01(\v2;.openshell.gateway_interceptor.v1.ModifyOperationEvaluationH\x00R\x0fmodifyOperation\x12R\n" +
	"\bvalidate\x18\a \x01(\v24.openshell.gateway_interceptor.v1.ValidateEvaluationH\x00R\bvalidate\x12Y\n" +
	"\vpost_commit\x18\b \x01(\v26.openshell.gateway_interceptor.v1.PostCommitEvaluationH\x00R\n" +
	"postCommit\x1a<\n" +
	"\x0ePrincipalEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05phase\"c\n" +
	"\x19ModifyOperationEvaluation\x12F\n" +
	"\x12proposed_operation\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x11proposedOperation\"\x9a\x01\n" +
	"\x12ValidateEvaluation\x12F\n" +
	"\x12proposed_operation\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x11proposedOperation\x12<\n" +
	"\rcurrent_state\x18\x02 \x01(\v2\x17.google.protobuf.StructR\fcurrentState\"^\n" +
	"\x14PostCommitEvaluation\x12F\n" +
	"\x12committed_response\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x11committedResponse\"\xe2\x02\n" +
	"\x11InterceptorResult\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\tR\n" +
	"statusCode\x12E\n" +
	"\apatches\x18\x04 \x03(\v2+.openshell.gateway_interceptor.v1.JsonPatchR\apatches\x12p\n" +
	"\x0flog_annotations\x18\x05 \x03(\v2G.openshell.gateway_interceptor.v1.InterceptorResult.LogAnnotationsEntryR\x0elogAnnotations\x1aA\n" +
	"\x13LogAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x13InterceptorManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12P\n" +
	"\bbindings\x18\x02 \x03(\v24.openshell.gateway_interceptor.v1.InterceptorBindingR\bbindings\x12%\n" +
	"\x0efailure_policy\x18\x03 \x01(\tR\rfailurePolicy\x12+\n" +
	"\x11provider_profiles\x18\x04 \x01(\bR\x10providerProfiles\x12+\n" +
	"\x11expected_audience\x18\x05 \x01(\tR\x10expectedAudience\"p\n" +
	"\x17ProviderProfileSnapshot\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\tR\brevision\x129\n" +
	"\bprofiles\x18\x02 \x03(\v2\x1d.openshell.v1.ProviderProfileR\bprofiles\"\xf1\x01\n" +
	"\x12InterceptorBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12Q\n" +
	"\bselector\x18\x02 \x01(\v25.openshell.gateway_interceptor.v1.InterceptorSelectorR\bselector\x12Q\n" +
	"\x06phases\x18\x03 \x03(\x0e29.openshell.gateway_interceptor.v1.GatewayInterceptorPhaseR\x06phases\x12%\n" +
	"\x0efailure_policy\x18\x04 \x01(\tR\rfailurePolicy\"Y\n" +
	"\x13InterceptorSelector\x12\x10\n" +
	"\x03rpc\x18\x01 \x01(\tR\x03rpc\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"q\n" +
	"\tJsonPatch\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from*\xc7\x01\n" +
	"\x17GatewayInterceptorPhase\x12)\n" +
	"%GATEWAY_INTERCEPTOR_PHASE_UNSPECIFIED\x10\x00\x12.\n" +
	"*GATEWAY_INTERCEPTOR_PHASE_MODIFY_OPERATION\x10\x02\x12&\n" +
	"\"GATEWAY_INTERCEPTOR_PHASE_VALIDATE\x10\x03\x12)\n" +
	"%GATEWAY_INTERCEPTOR_PHASE_POST_COMMIT\x10\x042\x9e\x03\n" +
	"\x12GatewayInterceptor\x12t\n" +
	"\bDescribe\x121.openshell.gateway_interceptor.v1.DescribeRequest\x1a5.openshell.gateway_interceptor.v1.InterceptorManifest\x12\x97\x01\n" +
	"\x18SnapshotProviderProfiles\x12@.openshell.gateway_interceptor.v1.ProviderProfileSnapshotRequest\x1a9.openshell.gateway_interceptor.v1.ProviderProfileSnapshot\x12x\n" +
	"\bEvaluate\x127.openshell.gateway_interceptor.v1.InterceptorEvaluation\x1a3.openshell.gateway_interceptor.v1.InterceptorResultb\x06proto3"

var (
	file_gateway_interceptor_proto_rawDescOnce sync.Once
	file_gateway_interceptor_proto_rawDescData []byte
)

func file_gateway_interceptor_proto_rawDescGZIP() []byte {
	file_gateway_interceptor_proto_rawDescOnce.Do(func() {
		file_gateway_interceptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_interceptor_proto_rawDesc), len(file_gateway_interceptor_proto_rawDesc)))
	})
	return file_gateway_interceptor_proto_rawDescData
}

var file_gateway_interceptor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_interceptor_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gateway_interceptor_proto_goTypes = []any{
	(GatewayInterceptorPhase)(0),           // 0: openshell.gateway_interceptor.v1.GatewayInterceptorPhase
	(*DescribeRequest)(nil),                // 1: openshell.gateway_interceptor.v1.DescribeRequest
	(*ProviderProfileSnapshotRequest)(nil), // 2: openshell.gateway_interceptor.v1.ProviderProfileSnapshotRequest
	(*InterceptorEvaluation)(nil),          // 3: openshell.gateway_interceptor.v1.InterceptorEvaluation
	(*ModifyOperationEvaluation)(nil),      // 4: openshell.gateway_interceptor.v1.ModifyOperationEvaluation
	(*ValidateEvaluation)(nil),             // 5: openshell.gateway_interceptor.v1.ValidateEvaluation
	(*PostCommitEvaluation)(nil),           // 6: openshell.gateway_interceptor.v1.PostCommitEvaluation
	(*InterceptorResult)(nil),              // 7: openshell.gateway_interceptor.v1.InterceptorResult
	(*InterceptorManifest)(nil),            // 8: openshell.gateway_interceptor.v1.InterceptorManifest
	(*ProviderProfileSnapshot)(nil),        // 9: openshell.gateway_interceptor.v1.ProviderProfileSnapshot
	(*InterceptorBinding)(nil),             // 10: openshell.gateway_interceptor.v1.InterceptorBinding
	(*InterceptorSelector)(nil),            // 11: openshell.gateway_interceptor.v1.InterceptorSelector
	(*JsonPatch)(nil),                      // 12: openshell.gateway_interceptor.v1.JsonPatch
	nil,                                    // 13: openshell.gateway_interceptor.v1.InterceptorEvaluation.PrincipalEntry
	nil,                                    // 14: openshell.gateway_interceptor.v1.InterceptorResult.LogAnnotationsEntry
	(*structpb.Struct)(nil),                // 15: google.protobuf.Struct
	(*openshellv1.ProviderProfile)(nil),    // 16: openshell.v1.ProviderProfile
	(*structpb.Value)(nil),                 // 17: google.protobuf.Value
}
var file_gateway_interceptor_proto_depIdxs = []int32{
	13, // 0: openshell.gateway_interceptor.v1.InterceptorEvaluation.principal:type_name -> openshell.gateway_interceptor.v1.InterceptorEvaluation.PrincipalEntry
	4,  // 1: openshell.gateway_interceptor.v1.InterceptorEvaluation.modify_operation:type_name -> openshell.gateway_interceptor.v1.ModifyOperationEvaluation
	5,  // 2: openshell.gateway_interceptor.v1.InterceptorEvaluation.validate:type_name -> openshell.gateway_interceptor.v1.ValidateEvaluation
	6,  // 3: openshell.gateway_interceptor.v1.InterceptorEvaluation.post_commit:type_name -> openshell.gateway_interceptor.v1.PostCommitEvaluation
	15, // 4: openshell.gateway_interceptor.v1.ModifyOperationEvaluation.proposed_operation:type_name -> google.protobuf.Struct
	15, // 5: openshell.gateway_interceptor.v1.ValidateEvaluation.proposed_operation:type_name -> google.protobuf.Struct
	15, // 6: openshell.gateway_interceptor.v1.ValidateEvaluation.current_state:type_name -> google.protobuf.Struct
	15, // 7: openshell.gateway_interceptor.v1.PostCommitEvaluation.committed_response:type_name -> google.protobuf.Struct
	12, // 8: openshell.gateway_interceptor.v1.InterceptorResult.patches:type_name -> openshell.gateway_interceptor.v1.JsonPatch
	14, // 9: openshell.gateway_interceptor.v1.InterceptorResult.log_annotations:type_name -> openshell.gateway_interceptor.v1.InterceptorResult.LogAnnotationsEntry
	10, // 10: openshell.gateway_interceptor.v1.InterceptorManifest.bindings:type_name -> openshell.gateway_interceptor.v1.InterceptorBinding
	16, // 11: openshell.gateway_interceptor.v1.ProviderProfileSnapshot.profiles:type_name -> openshell.v1.ProviderProfile
	11, // 12: openshell.gateway_interceptor.v1.InterceptorBinding.selector:type_name -> openshell.gateway_interceptor.v1.InterceptorSelector
	0,  // 13: openshell.gateway_interceptor.v1.InterceptorBinding.phases:type_name -> openshell.gateway_interceptor.v1.GatewayInterceptorPhase
	17, // 14: openshell.gateway_interceptor.v1.JsonPatch.value:type_name -> google.protobuf.Value
	1,  // 15: openshell.gateway_interceptor.v1.GatewayInterceptor.Describe:input_type -> openshell.gateway_interceptor.v1.DescribeRequest
	2,  // 16: openshell.gateway_interceptor.v1.GatewayInterceptor.SnapshotProviderProfiles:input_type -> openshell.gateway_interceptor.v1.ProviderProfileSnapshotRequest
	3,  // 17: openshell.gateway_interceptor.v1.GatewayInterceptor.Evaluate:input_type -> openshell.gateway_interceptor.v1.InterceptorEvaluation
	8,  // 18: openshell.gateway_interceptor.v1.GatewayInterceptor.Describe:output_type -> openshell.gateway_interceptor.v1.InterceptorManifest
	9,  // 19: openshell.gateway_interceptor.v1.GatewayInterceptor.SnapshotProviderProfiles:output_type -> openshell.gateway_interceptor.v1.ProviderProfileSnapshot
	7,  // 20: openshell.gateway_interceptor.v1.GatewayInterceptor.Evaluate:output_type -> openshell.gateway_interceptor.v1.InterceptorResult
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_gateway_interceptor_proto_init() }
func file_gateway_interceptor_proto_init() {
	if File_gateway_interceptor_proto != nil {
		return
	}
	file_gateway_interceptor_proto_msgTypes[2].OneofWrappers = []any{
		(*InterceptorEvaluation_ModifyOperation)(nil),
		(*InterceptorEvaluation_Validate)(nil),
		(*InterceptorEvaluation_PostCommit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_interceptor_proto_rawDesc), len(file_gateway_interceptor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_interceptor_proto_goTypes,
		DependencyIndexes: file_gateway_interceptor_proto_depIdxs,
		EnumInfos:         file_gateway_interceptor_proto_enumTypes,
		MessageInfos:      file_gateway_interceptor_proto_msgTypes,
	}.Build()
	File_gateway_interceptor_proto = out.File
	file_gateway_interceptor_proto_goTypes = nil
	file_gateway_interceptor_proto_depIdxs = nil
}
