// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: credential_driver.proto

package credentialsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialDriver_GetCapabilities_FullMethodName    = "/openshell.credentials.v1.CredentialDriver/GetCapabilities"
	CredentialDriver_StoreCredential_FullMethodName    = "/openshell.credentials.v1.CredentialDriver/StoreCredential"
	CredentialDriver_DeleteCredential_FullMethodName   = "/openshell.credentials.v1.CredentialDriver/DeleteCredential"
	CredentialDriver_ResolveCredentials_FullMethodName = "/openshell.credentials.v1.CredentialDriver/ResolveCredentials"
	CredentialDriver_ListCredentials_FullMethodName    = "/openshell.credentials.v1.CredentialDriver/ListCredentials"
)

// CredentialDriverClient is the client API for CredentialDriver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal credential-driver contract used by the gateway.
//
// The gateway owns provider semantics and sandbox delivery. Credential drivers
// own backend-specific storage, deletion, authentication, and lookup for
// gateway-managed provider-secret handles. Secrets include injectable provider
// credentials and gateway-only refresh material.
type CredentialDriverClient interface {
	// Report driver identity and feature support.
	GetCapabilities(ctx context.Context, in *GetCredentialDriverCapabilitiesRequest, opts ...grpc.CallOption) (*GetCredentialDriverCapabilitiesResponse, error)
	// Store or overwrite one gateway-managed provider secret and return an opaque handle.
	StoreCredential(ctx context.Context, in *StoreCredentialRequest, opts ...grpc.CallOption) (*StoreCredentialResponse, error)
	// Delete one provider credential handle.
	DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error)
	// Resolve a batch of credential handles into string secret values.
	ResolveCredentials(ctx context.Context, in *ResolveCredentialsRequest, opts ...grpc.CallOption) (*ResolveCredentialsResponse, error)
	// Optionally list discoverable credentials. Drivers may return UNIMPLEMENTED.
	ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error)
}

type credentialDriverClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialDriverClient(cc grpc.ClientConnInterface) CredentialDriverClient {
	return &credentialDriverClient{cc}
}

func (c *credentialDriverClient) GetCapabilities(ctx context.Context, in *GetCredentialDriverCapabilitiesRequest, opts ...grpc.CallOption) (*GetCredentialDriverCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialDriverCapabilitiesResponse)
	err := c.cc.Invoke(ctx, CredentialDriver_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialDriverClient) StoreCredential(ctx context.Context, in *StoreCredentialRequest, opts ...grpc.CallOption) (*StoreCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialDriver_StoreCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialDriverClient) DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialDriver_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialDriverClient) ResolveCredentials(ctx context.Context, in *ResolveCredentialsRequest, opts ...grpc.CallOption) (*ResolveCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveCredentialsResponse)
	err := c.cc.Invoke(ctx, CredentialDriver_ResolveCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialDriverClient) ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCredentialsResponse)
	err := c.cc.Invoke(ctx, CredentialDriver_ListCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialDriverServer is the server API for CredentialDriver service.
// All implementations must embed UnimplementedCredentialDriverServer
// for forward compatibility.
//
// Internal credential-driver contract used by the gateway.
//
// The gateway owns provider semantics and sandbox delivery. Credential drivers
// own backend-specific storage, deletion, authentication, and lookup for
// gateway-managed provider-secret handles. Secrets include injectable provider
// credentials and gateway-only refresh material.
type CredentialDriverServer interface {
	// Report driver identity and feature support.
	GetCapabilities(context.Context, *GetCredentialDriverCapabilitiesRequest) (*GetCredentialDriverCapabilitiesResponse, error)
	// Store or overwrite one gateway-managed provider secret and return an opaque handle.
	StoreCredential(context.Context, *StoreCredentialRequest) (*StoreCredentialResponse, error)
	// Delete one provider credential handle.
	DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error)
	// Resolve a batch of credential handles into string secret values.
	ResolveCredentials(context.Context, *ResolveCredentialsRequest) (*ResolveCredentialsResponse, error)
	// Optionally list discoverable credentials. Drivers may return UNIMPLEMENTED.
	ListCredentials(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error)
	mustEmbedUnimplementedCredentialDriverServer()
}

// UnimplementedCredentialDriverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialDriverServer struct{}

func (UnimplementedCredentialDriverServer) GetCapabilities(context.Context, *GetCredentialDriverCapabilitiesRequest) (*GetCredentialDriverCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedCredentialDriverServer) StoreCredential(context.Context, *StoreCredentialRequest) (*StoreCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreCredential not implemented")
}
func (UnimplementedCredentialDriverServer) DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedCredentialDriverServer) ResolveCredentials(context.Context, *ResolveCredentialsRequest) (*ResolveCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveCredentials not implemented")
}
func (UnimplementedCredentialDriverServer) ListCredentials(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCredentials not implemented")
}
func (UnimplementedCredentialDriverServer) mustEmbedUnimplementedCredentialDriverServer() {}
func (UnimplementedCredentialDriverServer) testEmbeddedByValue()                          {}

// UnsafeCredentialDriverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialDriverServer will
// result in compilation errors.
type UnsafeCredentialDriverServer interface {
	mustEmbedUnimplementedCredentialDriverServer()
}

func RegisterCredentialDriverServer(s grpc.ServiceRegistrar, srv CredentialDriverServer) {
	// If the following call panics, it indicates UnimplementedCredentialDriverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialDriver_ServiceDesc, srv)
}

func _CredentialDriver_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialDriverCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialDriverServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialDriver_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialDriverServer).GetCapabilities(ctx, req.(*GetCredentialDriverCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialDriver_StoreCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialDriverServer).StoreCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialDriver_StoreCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialDriverServer).StoreCredential(ctx, req.(*StoreCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialDriver_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialDriverServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialDriver_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialDriverServer).DeleteCredential(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialDriver_ResolveCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialDriverServer).ResolveCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialDriver_ResolveCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialDriverServer).ResolveCredentials(ctx, req.(*ResolveCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialDriver_ListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialDriverServer).ListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialDriver_ListCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialDriverServer).ListCredentials(ctx, req.(*ListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialDriver_ServiceDesc is the grpc.ServiceDesc for CredentialDriver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialDriver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openshell.credentials.v1.CredentialDriver",
	HandlerType: (*CredentialDriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _CredentialDriver_GetCapabilities_Handler,
		},
		{
			MethodName: "StoreCredential",
			Handler:    _CredentialDriver_StoreCredential_Handler,
		},
		{
			MethodName: "DeleteCredential",
			Handler:    _CredentialDriver_DeleteCredential_Handler,
		},
		{
			MethodName: "ResolveCredentials",
			Handler:    _CredentialDriver_ResolveCredentials_Handler,
		},
		{
			MethodName: "ListCredentials",
			Handler:    _CredentialDriver_ListCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credential_driver.proto",
}
