// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: credential_driver.proto

package credentialsv1

import (
	datamodelv1 "github.com/NVIDIA/OpenShell/sdk/go/proto/datamodelv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCredentialDriverCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialDriverCapabilitiesRequest) Reset() {
	*x = GetCredentialDriverCapabilitiesRequest{}
	mi := &file_credential_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialDriverCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialDriverCapabilitiesRequest) ProtoMessage() {}

func (x *GetCredentialDriverCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialDriverCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialDriverCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{0}
}

type GetCredentialDriverCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable driver name.
	DriverName string `protobuf:"bytes,1,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	// Driver implementation version string.
	DriverVersion string `protobuf:"bytes,2,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	// Backend kind, such as "kubernetes-secrets" or "vault".
	BackendKind string `protobuf:"bytes,3,opt,name=backend_kind,json=backendKind,proto3" json:"backend_kind,omitempty"`
	// True when ListCredentials is supported.
	SupportsList bool `protobuf:"varint,4,opt,name=supports_list,json=supportsList,proto3" json:"supports_list,omitempty"`
	// True when ResolveCredentials may return expires_at_ms values.
	SupportsExpiresAt bool `protobuf:"varint,5,opt,name=supports_expires_at,json=supportsExpiresAt,proto3" json:"supports_expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCredentialDriverCapabilitiesResponse) Reset() {
	*x = GetCredentialDriverCapabilitiesResponse{}
	mi := &file_credential_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialDriverCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialDriverCapabilitiesResponse) ProtoMessage() {}

func (x *GetCredentialDriverCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialDriverCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialDriverCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{1}
}

func (x *GetCredentialDriverCapabilitiesResponse) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *GetCredentialDriverCapabilitiesResponse) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GetCredentialDriverCapabilitiesResponse) GetBackendKind() string {
	if x != nil {
		return x.BackendKind
	}
	return ""
}

func (x *GetCredentialDriverCapabilitiesResponse) GetSupportsList() bool {
	if x != nil {
		return x.SupportsList
	}
	return false
}

func (x *GetCredentialDriverCapabilitiesResponse) GetSupportsExpiresAt() bool {
	if x != nil {
		return x.SupportsExpiresAt
	}
	return false
}

type StoreCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider instance name supplied for audit and backend policy decisions.
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Gateway-owned logical key for this provider secret. Injectable credentials
	// use their runtime environment key; refresh material uses an internal key.
	CredentialKey string `protobuf:"bytes,2,opt,name=credential_key,json=credentialKey,proto3" json:"credential_key,omitempty"`
	// Secret value to store. Drivers must never log this field.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Existing handle to overwrite, if any.
	ExistingHandle *datamodelv1.CredentialHandle `protobuf:"bytes,4,opt,name=existing_handle,json=existingHandle,proto3" json:"existing_handle,omitempty"`
	// Workspace that owns this provider. Used to ensure cross-workspace uniqueness.
	Workspace string `protobuf:"bytes,5,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// Provider UUID. Combined with workspace to ensure globally unique backend paths.
	ProviderId string `protobuf:"bytes,6,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Per-write backend object identity. When empty, drivers use provider_id.
	// Refreshes set this to a unique value so a staged write cannot overwrite the
	// currently committed object while provider_id remains the immutable owner.
	ObjectId      string `protobuf:"bytes,7,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreCredentialRequest) Reset() {
	*x = StoreCredentialRequest{}
	mi := &file_credential_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCredentialRequest) ProtoMessage() {}

func (x *StoreCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCredentialRequest.ProtoReflect.Descriptor instead.
func (*StoreCredentialRequest) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{2}
}

func (x *StoreCredentialRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *StoreCredentialRequest) GetCredentialKey() string {
	if x != nil {
		return x.CredentialKey
	}
	return ""
}

func (x *StoreCredentialRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StoreCredentialRequest) GetExistingHandle() *datamodelv1.CredentialHandle {
	if x != nil {
		return x.ExistingHandle
	}
	return nil
}

func (x *StoreCredentialRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *StoreCredentialRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *StoreCredentialRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type StoreCredentialResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque handle for later resolution/deletion.
	Handle        *datamodelv1.CredentialHandle `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreCredentialResponse) Reset() {
	*x = StoreCredentialResponse{}
	mi := &file_credential_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCredentialResponse) ProtoMessage() {}

func (x *StoreCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCredentialResponse.ProtoReflect.Descriptor instead.
func (*StoreCredentialResponse) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{3}
}

func (x *StoreCredentialResponse) GetHandle() *datamodelv1.CredentialHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

type DeleteCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider instance name supplied for audit and backend policy decisions.
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Gateway-owned logical key that owns the handle.
	CredentialKey string `protobuf:"bytes,2,opt,name=credential_key,json=credentialKey,proto3" json:"credential_key,omitempty"`
	// Opaque handle to delete.
	Handle *datamodelv1.CredentialHandle `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	// Workspace that owns this provider. Used to ensure cross-workspace uniqueness.
	Workspace string `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// Provider UUID. Combined with workspace to ensure globally unique backend paths.
	ProviderId    string `protobuf:"bytes,5,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_credential_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCredentialRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *DeleteCredentialRequest) GetCredentialKey() string {
	if x != nil {
		return x.CredentialKey
	}
	return ""
}

func (x *DeleteCredentialRequest) GetHandle() *datamodelv1.CredentialHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *DeleteCredentialRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DeleteCredentialRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type DeleteCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialResponse) Reset() {
	*x = DeleteCredentialResponse{}
	mi := &file_credential_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialResponse) ProtoMessage() {}

func (x *DeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{5}
}

type ResolveCredentialsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Credentials   []*ResolveCredentialRequest `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCredentialsRequest) Reset() {
	*x = ResolveCredentialsRequest{}
	mi := &file_credential_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCredentialsRequest) ProtoMessage() {}

func (x *ResolveCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ResolveCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveCredentialsRequest) GetCredentials() []*ResolveCredentialRequest {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type ResolveCredentialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway-chosen opaque ID used to correlate batch responses.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Provider instance name supplied for audit and backend policy decisions.
	ProviderName string `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// Gateway-owned logical key for the value being resolved.
	CredentialKey string `protobuf:"bytes,3,opt,name=credential_key,json=credentialKey,proto3" json:"credential_key,omitempty"`
	// Opaque handle to resolve.
	Handle *datamodelv1.CredentialHandle `protobuf:"bytes,4,opt,name=handle,proto3" json:"handle,omitempty"`
	// Workspace that owns this provider. Used to ensure cross-workspace uniqueness.
	Workspace string `protobuf:"bytes,5,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// Provider UUID. Combined with workspace to ensure globally unique backend paths.
	ProviderId    string `protobuf:"bytes,6,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCredentialRequest) Reset() {
	*x = ResolveCredentialRequest{}
	mi := &file_credential_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCredentialRequest) ProtoMessage() {}

func (x *ResolveCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCredentialRequest.ProtoReflect.Descriptor instead.
func (*ResolveCredentialRequest) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveCredentialRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResolveCredentialRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ResolveCredentialRequest) GetCredentialKey() string {
	if x != nil {
		return x.CredentialKey
	}
	return ""
}

func (x *ResolveCredentialRequest) GetHandle() *datamodelv1.CredentialHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *ResolveCredentialRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ResolveCredentialRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type ResolveCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*ResolvedCredential  `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCredentialsResponse) Reset() {
	*x = ResolveCredentialsResponse{}
	mi := &file_credential_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCredentialsResponse) ProtoMessage() {}

func (x *ResolveCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ResolveCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveCredentialsResponse) GetCredentials() []*ResolvedCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type ResolvedCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes ResolveCredentialRequest.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Secret string value. Drivers must never log this field.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Expiration timestamp in milliseconds since Unix epoch, or zero when absent.
	ExpiresAtMs   int64 `protobuf:"varint,3,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedCredential) Reset() {
	*x = ResolvedCredential{}
	mi := &file_credential_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedCredential) ProtoMessage() {}

func (x *ResolvedCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedCredential.ProtoReflect.Descriptor instead.
func (*ResolvedCredential) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{9}
}

func (x *ResolvedCredential) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResolvedCredential) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResolvedCredential) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

type ListCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsRequest) Reset() {
	*x = ListCredentialsRequest{}
	mi := &file_credential_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsRequest) ProtoMessage() {}

func (x *ListCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{10}
}

type ListCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*ListedCredential    `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsResponse) Reset() {
	*x = ListCredentialsResponse{}
	mi := &file_credential_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsResponse) ProtoMessage() {}

func (x *ListCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{11}
}

func (x *ListCredentialsResponse) GetCredentials() []*ListedCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type ListedCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque handle identifier or driver-owned display name.
	Handle string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// Available credential keys under the backend object.
	Keys []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	// Driver-owned non-secret metadata.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListedCredential) Reset() {
	*x = ListedCredential{}
	mi := &file_credential_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListedCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListedCredential) ProtoMessage() {}

func (x *ListedCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credential_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListedCredential.ProtoReflect.Descriptor instead.
func (*ListedCredential) Descriptor() ([]byte, []int) {
	return file_credential_driver_proto_rawDescGZIP(), []int{12}
}

func (x *ListedCredential) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *ListedCredential) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListedCredential) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_credential_driver_proto protoreflect.FileDescriptor

const file_credential_driver_proto_rawDesc = "" +
	"\n" +
	"\x17credential_driver.proto\x12\x18openshell.credentials.v1\x1a\x0fdatamodel.proto\"(\n" +
	"&GetCredentialDriverCapabilitiesRequest\"\xe9\x01\n" +
	"'GetCredentialDriverCapabilitiesResponse\x12\x1f\n" +
	"\vdriver_name\x18\x01 \x01(\tR\n" +
	"driverName\x12%\n" +
	"\x0edriver_version\x18\x02 \x01(\tR\rdriverVersion\x12!\n" +
	"\fbackend_kind\x18\x03 \x01(\tR\vbackendKind\x12#\n" +
	"\rsupports_list\x18\x04 \x01(\bR\fsupportsList\x12.\n" +
	"\x13supports_expires_at\x18\x05 \x01(\bR\x11supportsExpiresAt\"\xa9\x02\n" +
	"\x16StoreCredentialRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12%\n" +
	"\x0ecredential_key\x18\x02 \x01(\tR\rcredentialKey\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12Q\n" +
	"\x0fexisting_handle\x18\x04 \x01(\v2(.openshell.datamodel.v1.CredentialHandleR\x0eexistingHandle\x12\x1c\n" +
	"\tworkspace\x18\x05 \x01(\tR\tworkspace\x12\x1f\n" +
	"\vprovider_id\x18\x06 \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tobject_id\x18\a \x01(\tR\bobjectId\"[\n" +
	"\x17StoreCredentialResponse\x12@\n" +
	"\x06handle\x18\x01 \x01(\v2(.openshell.datamodel.v1.CredentialHandleR\x06handle\"\xe6\x01\n" +
	"\x17DeleteCredentialRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12%\n" +
	"\x0ecredential_key\x18\x02 \x01(\tR\rcredentialKey\x12@\n" +
	"\x06handle\x18\x03 \x01(\v2(.openshell.datamodel.v1.CredentialHandleR\x06handle\x12\x1c\n" +
	"\tworkspace\x18\x04 \x01(\tR\tworkspace\x12\x1f\n" +
	"\vprovider_id\x18\x05 \x01(\tR\n" +
	"providerId\"\x1a\n" +
	"\x18DeleteCredentialResponse\"q\n" +
	"\x19ResolveCredentialsRequest\x12T\n" +
	"\vcredentials\x18\x01 \x03(\v22.openshell.credentials.v1.ResolveCredentialRequestR\vcredentials\"\x86\x02\n" +
	"\x18ResolveCredentialRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12%\n" +
	"\x0ecredential_key\x18\x03 \x01(\tR\rcredentialKey\x12@\n" +
	"\x06handle\x18\x04 \x01(\v2(.openshell.datamodel.v1.CredentialHandleR\x06handle\x12\x1c\n" +
	"\tworkspace\x18\x05 \x01(\tR\tworkspace\x12\x1f\n" +
	"\vprovider_id\x18\x06 \x01(\tR\n" +
	"providerId\"l\n" +
	"\x1aResolveCredentialsResponse\x12N\n" +
	"\vcredentials\x18\x01 \x03(\v2,.openshell.credentials.v1.ResolvedCredentialR\vcredentials\"m\n" +
	"\x12ResolvedCredential\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\"\n" +
	"\rexpires_at_ms\x18\x03 \x01(\x03R\vexpiresAtMs\"\x18\n" +
	"\x16ListCredentialsRequest\"g\n" +
	"\x17ListCredentialsResponse\x12L\n" +
	"\vcredentials\x18\x01 \x03(\v2*.openshell.credentials.v1.ListedCredentialR\vcredentials\"\xd1\x01\n" +
	"\x10ListedCredential\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x12T\n" +
	"\bmetadata\x18\x03 \x03(\v28.openshell.credentials.v1.ListedCredential.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x97\x05\n" +
	"\x10CredentialDriver\x12\x96\x01\n" +
	"\x0fGetCapabilities\x12@.openshell.credentials.v1.GetCredentialDriverCapabilitiesRequest\x1aA.openshell.credentials.v1.GetCredentialDriverCapabilitiesResponse\x12v\n" +
	"\x0fStoreCredential\x120.openshell.credentials.v1.StoreCredentialRequest\x1a1.openshell.credentials.v1.StoreCredentialResponse\x12y\n" +
	"\x10DeleteCredential\x121.openshell.credentials.v1.DeleteCredentialRequest\x1a2.openshell.credentials.v1.DeleteCredentialResponse\x12\x7f\n" +
	"\x12ResolveCredentials\x123.openshell.credentials.v1.ResolveCredentialsRequest\x1a4.openshell.credentials.v1.ResolveCredentialsResponse\x12v\n" +
	"\x0fListCredentials\x120.openshell.credentials.v1.ListCredentialsRequest\x1a1.openshell.credentials.v1.ListCredentialsResponseb\x06proto3"

var (
	file_credential_driver_proto_rawDescOnce sync.Once
	file_credential_driver_proto_rawDescData []byte
)

func file_credential_driver_proto_rawDescGZIP() []byte {
	file_credential_driver_proto_rawDescOnce.Do(func() {
		file_credential_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credential_driver_proto_rawDesc), len(file_credential_driver_proto_rawDesc)))
	})
	return file_credential_driver_proto_rawDescData
}

var file_credential_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_credential_driver_proto_goTypes = []any{
	(*GetCredentialDriverCapabilitiesRequest)(nil),  // 0: openshell.credentials.v1.GetCredentialDriverCapabilitiesRequest
	(*GetCredentialDriverCapabilitiesResponse)(nil), // 1: openshell.credentials.v1.GetCredentialDriverCapabilitiesResponse
	(*StoreCredentialRequest)(nil),                  // 2: openshell.credentials.v1.StoreCredentialRequest
	(*StoreCredentialResponse)(nil),                 // 3: openshell.credentials.v1.StoreCredentialResponse
	(*DeleteCredentialRequest)(nil),                 // 4: openshell.credentials.v1.DeleteCredentialRequest
	(*DeleteCredentialResponse)(nil),                // 5: openshell.credentials.v1.DeleteCredentialResponse
	(*ResolveCredentialsRequest)(nil),               // 6: openshell.credentials.v1.ResolveCredentialsRequest
	(*ResolveCredentialRequest)(nil),                // 7: openshell.credentials.v1.ResolveCredentialRequest
	(*ResolveCredentialsResponse)(nil),              // 8: openshell.credentials.v1.ResolveCredentialsResponse
	(*ResolvedCredential)(nil),                      // 9: openshell.credentials.v1.ResolvedCredential
	(*ListCredentialsRequest)(nil),                  // 10: openshell.credentials.v1.ListCredentialsRequest
	(*ListCredentialsResponse)(nil),                 // 11: openshell.credentials.v1.ListCredentialsResponse
	(*ListedCredential)(nil),                        // 12: openshell.credentials.v1.ListedCredential
	nil,                                             // 13: openshell.credentials.v1.ListedCredential.MetadataEntry
	(*datamodelv1.CredentialHandle)(nil),            // 14: openshell.datamodel.v1.CredentialHandle
}
var file_credential_driver_proto_depIdxs = []int32{
	14, // 0: openshell.credentials.v1.StoreCredentialRequest.existing_handle:type_name -> openshell.datamodel.v1.CredentialHandle
	14, // 1: openshell.credentials.v1.StoreCredentialResponse.handle:type_name -> openshell.datamodel.v1.CredentialHandle
	14, // 2: openshell.credentials.v1.DeleteCredentialRequest.handle:type_name -> openshell.datamodel.v1.CredentialHandle
	7,  // 3: openshell.credentials.v1.ResolveCredentialsRequest.credentials:type_name -> openshell.credentials.v1.ResolveCredentialRequest
	14, // 4: openshell.credentials.v1.ResolveCredentialRequest.handle:type_name -> openshell.datamodel.v1.CredentialHandle
	9,  // 5: openshell.credentials.v1.ResolveCredentialsResponse.credentials:type_name -> openshell.credentials.v1.ResolvedCredential
	12, // 6: openshell.credentials.v1.ListCredentialsResponse.credentials:type_name -> openshell.credentials.v1.ListedCredential
	13, // 7: openshell.credentials.v1.ListedCredential.metadata:type_name -> openshell.credentials.v1.ListedCredential.MetadataEntry
	0,  // 8: openshell.credentials.v1.CredentialDriver.GetCapabilities:input_type -> openshell.credentials.v1.GetCredentialDriverCapabilitiesRequest
	2,  // 9: openshell.credentials.v1.CredentialDriver.StoreCredential:input_type -> openshell.credentials.v1.StoreCredentialRequest
	4,  // 10: openshell.credentials.v1.CredentialDriver.DeleteCredential:input_type -> openshell.credentials.v1.DeleteCredentialRequest
	6,  // 11: openshell.credentials.v1.CredentialDriver.ResolveCredentials:input_type -> openshell.credentials.v1.ResolveCredentialsRequest
	10, // 12: openshell.credentials.v1.CredentialDriver.ListCredentials:input_type -> openshell.credentials.v1.ListCredentialsRequest
	1,  // 13: openshell.credentials.v1.CredentialDriver.GetCapabilities:output_type -> openshell.credentials.v1.GetCredentialDriverCapabilitiesResponse
	3,  // 14: openshell.credentials.v1.CredentialDriver.StoreCredential:output_type -> openshell.credentials.v1.StoreCredentialResponse
	5,  // 15: openshell.credentials.v1.CredentialDriver.DeleteCredential:output_type -> openshell.credentials.v1.DeleteCredentialResponse
	8,  // 16: openshell.credentials.v1.CredentialDriver.ResolveCredentials:output_type -> openshell.credentials.v1.ResolveCredentialsResponse
	11, // 17: openshell.credentials.v1.CredentialDriver.ListCredentials:output_type -> openshell.credentials.v1.ListCredentialsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_credential_driver_proto_init() }
func file_credential_driver_proto_init() {
	if File_credential_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credential_driver_proto_rawDesc), len(file_credential_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credential_driver_proto_goTypes,
		DependencyIndexes: file_credential_driver_proto_depIdxs,
		MessageInfos:      file_credential_driver_proto_msgTypes,
	}.Build()
	File_credential_driver_proto = out.File
	file_credential_driver_proto_goTypes = nil
	file_credential_driver_proto_depIdxs = nil
}
